---
- name: Install tasks
  become: true
  tags:
    - sshd_install
    - sshd
  block:
    - name: Ensure packages
      ansible.builtin.package:
        name: "{{ sshd_package_name }}"
        state: present
