---

- name: main tasks
  tags:
    - sshd_install
    - sshd_config
    - sshd_service
    - sshd
  block:
    - name: load dependency variables
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - "{{ ansible_os_family }}/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"
    - name: sshd install tasks
      ansible.builtin.import_tasks: install.yml
    - name: sshd configration tasks
      ansible.builtin.import_tasks: config.yml
    - name: sshd dropin configration tasks
      ansible.builtin.import_tasks: dropin.yml
    - name: sshd service tasks
      ansible.builtin.import_tasks: service.yml
  rescue:
    - name: print Error
      ansible.builtin.debug:
        msg: "Unsupport platform or error occurred due to some reason."
      failed_when: true

