- name: Config tasks
  become: true
  tags:
    - sshd_config
    - sshd
  block:
    - name: Backup Diffie-Hellman moduli
      ansible.builtin.copy:
        src: /etc/ssh/moduli
        dest: /etc/ssh/moduli.orig
        owner: root
        group: root
        mode: '0644'
        remote_src: true
        force: false

    - name: Remove small Diffie-Hellman moduli
      ansible.builtin.shell:
        cmd: awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.safe
        creates: /etc/ssh/moduli.safe
      args:
        executable: /bin/bash

    - name: Replace Diffie-Hellman moduli
      ansible.builtin.file:
        src: /etc/ssh/moduli.safe
        dest: /etc/ssh/moduli
        state: link
        force: true
