---

- name: Service tasks
  become: true
  tags:
    - sshd_service
    - sshd
  block:
    - name: Ensure service
      ansible.builtin.service:
        name: "{{ sshd_service_name }}"
        state: "{{ sshd_service_ensure }}"
        enabled: "{{ sshd_service_enable }}"
