---
- name: Restart sshd
  ansible.builtin.systemd:
    name: "{{ sshd_service_name }}"
    state: restarted
  become: true

- name: Reload sshd
  ansible.builtin.systemd:
    name: "{{ sshd_service_name }}"
    state: reloaded
  become: true
