FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
  apt-get install -y --no-install-recommends python3 python3-apt sudo openssh-server ca-certificates && \
  mkdir -p /run/sshd && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 22
