---
driver:
  name: docker

platforms:
  - name: instance
    image: ubuntu-sshd-test:jammy   # ビルド後付くタグ
    build_image: true
    dockerfile: Dockerfile.ubuntu.jammy
    command: /usr/sbin/sshd -D -e
    privileged: false
    published_ports:
      - 0.0.0.0:2222:22

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
  requirements_file: ../../requirements.yml
  inventory:
    host_vars: {}
  config_options:
    defaults:
      stdout_callback: yaml
  env:
    ANSIBLE_DEPRECATION_WARNINGS: "False"

dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml
    force: true
    ignore-certs: true

verifier:
  name: ansible
