---
- name: Verify sshd
  hosts: all
  gather_facts: false
  tasks:
    - name: Check sshd process is running
      ansible.builtin.command: pgrep -x sshd
      register: sshd_pgrep
      changed_when: false
      failed_when: sshd_pgrep.rc != 0

    - name: Ensure port 22 is listening
      ansible.builtin.wait_for:
        port: 22
        state: started
        timeout: 10
