---

- name: Debug dropin config tasks
  when: sshd_debug is defined and sshd_debug
  block:
    - name: Print sshd_dropin_config_current
      ansible.builtin.debug:
        var: sshd_dropin_config_current
    - name: Print sshd_client_dropin_config_temp
      ansible.builtin.debug:
        var: sshd_client_dropin_config_temp
    - name: Print sshd_server_dropin_config_temp
      ansible.builtin.debug:
        var: sshd_server_dropin_config_temp
    - name: Print sshd_dropin_config_manage
      ansible.builtin.debug:
        var: sshd_dropin_config_manage
    - name: Print sshd_dropin_config_remove
      ansible.builtin.debug:
        var: sshd_dropin_config_remove
